export const UPDATE_FIELD_SIGN_IN = 'UPDATE_FIELD_SIGN_IN';
export const UPDATE_FIELD_SIGN_IN_ERROR = 'UPDATE_FIELD_SIGN_IN_ERROR';
export const UPDATE_FIELD_SIGN_UP = 'UPDATE_FIELD_SIGN_UP';
export const UPDATE_FIELD_SIGN_UP_SEND_EMAIL = 'UPDATE_FIELD_SIGN_UP_SEND_EMAIL';
export const GET_COUNTRY = 'GET_COUNTRY';
export const GET_DOCTOR = 'GET_DOCTOR';
